# Generated by Django 2.1.7 on 2019-02-21 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=15)),
                ('created_data', models.DateTimeField(default=datetime.datetime(2019, 2, 21, 14, 6, 21, 134977, tzinfo=utc))),
            ],
        ),
    ]
