# Generated by Django 2.1.7 on 2019-02-21 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20190221_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 14, 13, 51, 429916, tzinfo=utc)),
        ),
    ]
