# Generated by Django 2.1.7 on 2019-02-21 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20190221_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='created_data',
        ),
        migrations.AddField(
            model_name='ask',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 15, 39, 23, 955330, tzinfo=utc)),
        ),
    ]
