# Generated by Django 2.1.7 on 2019-02-23 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0018_auto_20190223_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
