# Generated by Django 2.1.7 on 2019-02-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0021_auto_20190223_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Post',
        ),
    ]
