# Generated by Django 2.1.7 on 2019-02-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0022_remove_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='basic_app.Ask'),
            preserve_default=False,
        ),
    ]
