# Generated by Django 2.1.7 on 2019-02-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0023_auto_20190223_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='gihub_link',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ask',
            name='linked_link',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
